rootUrl: ...
dockerImage: ...
auth:
  client_table_name: ...
  roles_container_name: ...
  static_clients: {}
  azure_accounts: {}
  sentry_organization: ...
  sentry_host: ...
  sentry_auth_token: ...
  sentry_team: ...
  sentry_key_prefix: ...
  statsum_api_secret: ...
  statsum_base_url: ...
  websocktunnel_secret: ...
  docs_bucket: ...
  schemas_bucket: ...
  refs_bucket: ...
  audit_log: ...
  azure_account: ...
  azure_account_key: ...
  azure_signing_key: ...
  azure_crypto_key: ...
  pulse_username: ...
  pulse_password: ...
  pulse_hostname: ...
  pulse_vhost: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
  aws_region: ...
  gcp_credentials: {}
  test_bucket: ...
built_in_workers:
  taskcluster_client_id: ...
  taskcluster_access_token: ...
github:
  bot_username: ...
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  github_private_pem: ...
  github_app_id: ...
  webhook_secret: []
  provisioner_id: ...
  worker_type: ...
  azure_account_name: ...
  pulse_hostname: ...
  pulse_username: ...
  pulse_password: ...
  pulse_vhost: ...
  pulse_namespace: ...
  aws_access_key: ...
  aws_secret_key: ...
hooks:
  hook_table_name: ...
  lastfire_table_name: ...
  queue_table_name: ...
  influx_connection: ...
  azure_account: ...
  table_signing_key: ...
  table_crypto_key: ...
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
  pulse_username: ...
  pulse_password: ...
  pulse_hostname: ...
  pulse_vhost: ...
index:
  azure_account: ...
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  pulse_hostname: ...
  pulse_username: ...
  pulse_password: ...
  pulse_vhost: ...
  pulse_namespace: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
login:
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
  auth0_domain: ...
  auth0_api_audience: ...
  auth0_client_id: ...
  auth0_client_secret: ...
notify:
  email_source_address: ...
  email_blacklist: {}
  denylisted_notification_table_name: ...
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  azure_account: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
  aws_region: ...
  pulse_namespace: ...
  pulse_hostname: ...
  pulse_username: ...
  pulse_password: ...
  pulse_vhost: ...
  irc_server: ...
  irc_nick: ...
  irc_user_name: ...
  irc_real_name: ...
  irc_password: ...
  irc_port: ...
  irc_debug: ...
  irc_pulse_queue_name: ...
purge_cache:
  azure_account: ...
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
queue:
  public_blob_artifact_bucket: ...
  private_blob_artifact_bucket: ...
  blob_artifact_region: ...
  public_artifact_bucket: ...
  private_artifact_bucket: ...
  azure_report_chance: 1
  azure_report_threshold: 1
  public_artifact_ec2_proxies: {}
  public_artifact_bucket_cdn: ...
  use_cloud_mirror: true/false
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  azure_account_id: ...
  azure_account_key: ...
  azure_table_account_name: ...
  pulse_namespace: ...
  pulse_username: ...
  pulse_password: ...
  pulse_hostname: ...
  pulse_vhost: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
  artifact_region: ...
secrets:
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  azure_account: ...
  azure_table_name: ...
  azure_crypto_key: ...
  azure_signing_key: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
treeherder:
  pulse_namespace: ...
  pulse_username: ...
  pulse_password: ...
  pulse_hostname: ...
  pulse_vhost: ...
  treeherder_route_prefix: ...
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
web_server:
  public_url: ...
  additional_allowed_cors_origin: ...
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  pulse_namespace: ...
  pulse_username: ...
  pulse_password: ...
  pulse_hostname: ...
  pulse_vhost: ...
  ui_login_strategies: {}
  jwt_key: ...
worker_manager:
  taskcluster_client_id: ...
  taskcluster_access_token: ...
  azure_account: ...
  pulse_hostname: ...
  pulse_username: ...
  pulse_password: ...
  pulse_vhost: ...
  pulse_namespace: ...
  providers: {}
ui: {}
references: {}
