apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${projectName}-${lowercase(procName)}
spec:
  schedule: ${schedule}
  jobTemplate:
    metadata:
      labels:
        application: taskcluster
        taskcluster-service: ${projectName}
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: {$eval: 'deadlineSeconds'}
          containers:
          - name: ${projectName}-${lowercase(procName)}
            image: '{{ .Values.dockerImage }}'
            imagePullPolicy: Always
            args: ['${serviceName}/${procName}']
            resources:
              # TODO: Make configurable
              requests:
                cpu: 100m
                memory: 100Mi
            env:
              $flatten:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
            envFrom:
              - secretRef:
                  name: ${projectName}
