apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${projectName}-${lowercase(procName)}
  labels:
    app.kubernetes.io/name: taskcluster-${projectName}
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: ${serviceName}-${procName}
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ${projectName}
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: ${serviceName}-${procName}
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: 1 # TODO
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/${projectName}-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: ${projectName}
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: ${serviceName}-${procName}
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: ${projectName}
      containers:
      - name: ${projectName}
        image: '{{ .Values.dockerImage }}'
        imagePullPolicy: Always
        args: ['${serviceName}/${procName}']
        resources:
          # TODO: Make configurable
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          $flatten:
            - $if: 'needsService'
              then:
                name: PORT
                value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
        envFrom:
            - secretRef:
                name: ${projectName}
        ports:
        - $if: 'needsService'
          then:
            containerPort: 80
        readinessProbe:
          $if: 'needsService'
          then:
            httpGet:
              path: ${readinessPath}
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 3
