apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${projectName}
data:
  $merge:
    $map: {$eval: secrets}
    each(s):
      ${uppercase(s.key)}: '{{ ${s.val} | toJson | trimAll "\"" | b64enc }}'
