kind: Service
apiVersion: v1
metadata:
  name: ${projectName}
spec:
  type: NodePort
  selector:
    application: taskcluster
    taskcluster-service: ${projectName}
    taskcluster-proc: ${procName}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
