apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-ui
data:
  APPLICATION_NAME: '{{ if typeIs "<nil>" .Values.ui.application_name }}{{ else }}{{ .Values.ui.application_name | toJson | trimAll "\"" | b64enc }}{{ end }}'
