apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-built-in-workers-server
  labels:
    app.kubernetes.io/name: taskcluster-taskcluster-built-in-workers
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: built-in-workers-server
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskcluster-built-in-workers
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: built-in-workers-server
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-built-in-workers-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: taskcluster-built-in-workers
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: built-in-workers-server
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: taskcluster-built-in-workers
      containers:
        - name: taskcluster-built-in-workers
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - built-in-workers/server
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-built-in-workers
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/built-in-workers/v1/ping
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 3
