apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-worker-manager
data:
  LEVEL: '{{ .Values.worker_manager.level | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ROOT_URL: '{{ .Values.worker_manager.taskcluster_root_url | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_CLIENT_ID: '{{ .Values.worker_manager.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ .Values.worker_manager.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}'
  AZURE_ACCOUNT_ID: '{{ .Values.azureAccountId | toJson | trimAll "\"" | b64enc }}'
  PORT: '{{ .Values.worker_manager.port | toJson | trimAll "\"" | b64enc }}'
  NODE_ENV: '{{ .Values.nodeEnv | toJson | trimAll "\"" | b64enc }}'
  FORCE_SSL: '{{ .Values.forceSSL | toJson | trimAll "\"" | b64enc }}'
  TRUST_PROXY: '{{ .Values.trustProxy | toJson | trimAll "\"" | b64enc }}'
  PULSE_HOSTNAME: '{{ .Values.pulseHostname | toJson | trimAll "\"" | b64enc }}'
  PULSE_USERNAME: '{{ .Values.worker_manager.pulse_username | toJson | trimAll "\"" | b64enc }}'
  PULSE_PASSWORD: '{{ .Values.worker_manager.pulse_password | toJson | trimAll "\"" | b64enc }}'
  PULSE_VHOST: '{{ .Values.pulseVhost | toJson | trimAll "\"" | b64enc }}'
  PULSE_NAMESPACE: '{{ .Values.worker_manager.pulse_namespace | toJson | trimAll "\"" | b64enc }}'
  PROVIDERS: '{{ .Values.worker_manager.providers | toJson | trimAll "\"" | b64enc }}'
