apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-worker-manager-workerscanner
spec:
  selector:
    matchLabels:
      application: taskcluster
      taskcluster-service: taskcluster-worker-manager
      taskcluster-proc: workerscanner
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-worker-manager-secret.yaml") . | sha256sum }}'
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-worker-manager
        taskcluster-proc: workerscanner
    spec:
      serviceAccountName: taskcluster-worker-manager
      containers:
        - name: taskcluster-worker-manager
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - worker-manager/workerscanner
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-worker-manager
          ports: []
