apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-web-server-scanner
spec:
  schedule: 0 0 * * *
  jobTemplate:
    metadata:
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-web-server
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 86400
          containers:
            - name: taskcluster-web-server-scanner
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - web-server/scanner
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
              envFrom:
                - secretRef:
                    name: taskcluster-web-server
