apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-index
data:
  AZURE_ACCOUNT_ID: '{{ if .Values.azureAccountId }}{{ .Values.azureAccountId | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  LEVEL: '{{ if .Values.index.level }}{{ .Values.index.level | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  PORT: '{{ if .Values.index.port }}{{ .Values.index.port | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  TASKCLUSTER_ROOT_URL: '{{ if .Values.index.taskcluster_root_url }}{{ .Values.index.taskcluster_root_url | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  TASKCLUSTER_CLIENT_ID: '{{ if .Values.index.taskcluster_client_id }}{{ .Values.index.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ if .Values.index.taskcluster_access_token }}{{ .Values.index.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  PULSE_HOSTNAME: '{{ if .Values.pulseHostname }}{{ .Values.pulseHostname | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  PULSE_USERNAME: '{{ if .Values.index.pulse_username }}{{ .Values.index.pulse_username | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  PULSE_PASSWORD: '{{ if .Values.index.pulse_password }}{{ .Values.index.pulse_password | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  PULSE_VHOST: '{{ if .Values.pulseVhost }}{{ .Values.pulseVhost | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  PULSE_NAMESPACE: '{{ if .Values.index.pulse_namespace }}{{ .Values.index.pulse_namespace | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AWS_ACCESS_KEY_ID: '{{ if .Values.index.aws_access_key_id }}{{ .Values.index.aws_access_key_id | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AWS_SECRET_ACCESS_KEY: '{{ if .Values.index.aws_secret_access_key }}{{ .Values.index.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  FORCE_SSL: '{{ if .Values.forceSSL }}{{ .Values.forceSSL | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  TRUST_PROXY: '{{ if .Values.trustProxy }}{{ .Values.trustProxy | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
