apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-queue-deadlineresolver
  labels:
    app.kubernetes.io/name: taskcluster-taskcluster-queue
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: queue-deadlineResolver
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskcluster-queue
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: queue-deadlineResolver
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-queue-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: taskcluster-queue
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: queue-deadlineResolver
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: taskcluster-queue
      containers:
        - name: taskcluster-queue
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - queue/deadlineResolver
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-queue
          ports: []
