apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-notify-web
spec:
  selector:
    matchLabels:
      application: taskcluster
      taskcluster-service: taskcluster-notify
      taskcluster-proc: web
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-notify-secret.yaml") . | sha256sum }}'
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-notify
        taskcluster-proc: web
    spec:
      serviceAccountName: taskcluster-notify
      containers:
        - name: taskcluster-notify
          image: .Values.dockerImage
          imagePullPolicy: Always
          args:
            - notify/web
          resources:
            requests:
              cpu: 1
              memory: 1
          env:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: .Values.rootUrl
          envFrom:
            - secretRef:
                name: taskcluster-notify
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/notify/v1/ping
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 3
