apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-hooks
data:
  HOOK_TABLE_NAME: '{{ .Values.hooks.hook_table_name | toJson | trimAll "\"" | b64enc }}'
  LASTFIRE_TABLE_NAME: '{{ .Values.hooks.lastfire_table_name | toJson | trimAll "\"" | b64enc }}'
  QUEUE_TABLE_NAME: '{{ .Values.hooks.queue_table_name | toJson | trimAll "\"" | b64enc }}'
  INFLUX_CONNECTION: '{{ .Values.hooks.influx_connection | toJson | trimAll "\"" | b64enc }}'
  AZURE_ACCOUNT_ID: '{{ .Values.azureAccountId | toJson | trimAll "\"" | b64enc }}'
  TABLE_SIGNING_KEY: '{{ .Values.hooks.table_signing_key | toJson | trimAll "\"" | b64enc }}'
  TABLE_CRYPTO_KEY: '{{ .Values.hooks.table_crypto_key | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ROOT_URL: '{{ .Values.hooks.taskcluster_root_url | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_CLIENT_ID: '{{ .Values.hooks.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ .Values.hooks.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}'
  LEVEL: '{{ .Values.hooks.level | toJson | trimAll "\"" | b64enc }}'
  PORT: '{{ .Values.hooks.port | toJson | trimAll "\"" | b64enc }}'
  NODE_ENV: '{{ .Values.nodeEnv | toJson | trimAll "\"" | b64enc }}'
  FORCE_SSL: '{{ .Values.forceSSL | toJson | trimAll "\"" | b64enc }}'
  TRUST_PROXY: '{{ .Values.trustProxy | toJson | trimAll "\"" | b64enc }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.hooks.aws_access_key_id | toJson | trimAll "\"" | b64enc }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.hooks.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}'
  PULSE_USERNAME: '{{ .Values.hooks.pulse_username | toJson | trimAll "\"" | b64enc }}'
  PULSE_PASSWORD: '{{ .Values.hooks.pulse_password | toJson | trimAll "\"" | b64enc }}'
  PULSE_HOSTNAME: '{{ .Values.pulseHostname | toJson | trimAll "\"" | b64enc }}'
  PULSE_VHOST: '{{ .Values.pulseVhost | toJson | trimAll "\"" | b64enc }}'
