apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-index-handlers
  labels:
    app.kubernetes.io/name: taskcluster-taskcluster-index
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: index-handlers
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskcluster-index
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: index-handlers
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-index-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: taskcluster-index
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: index-handlers
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: taskcluster-index
      containers:
        - name: taskcluster-index
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - index/handlers
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-index
          ports: []
