apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-queue-claimresolver
spec:
  selector:
    matchLabels:
      application: taskcluster
      taskcluster-service: taskcluster-queue
      taskcluster-proc: claimResolver
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-queue-secret.yaml") . | sha256sum }}'
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-queue
        taskcluster-proc: claimResolver
    spec:
      serviceAccountName: taskcluster-queue
      containers:
        - name: taskcluster-queue
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - queue/claimResolver
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-queue
          ports: []
