apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-secrets
data:
  - TASKCLUSTER_ROOT_URL: '{{ .Values.secrets.taskcluster_root_url | b64enc }}'
  - TASKCLUSTER_CLIENT_ID: '{{ .Values.secrets.taskcluster_client_id | b64enc }}'
  - TASKCLUSTER_ACCESS_TOKEN: '{{ .Values.secrets.taskcluster_access_token | b64enc }}'
  - AZURE_ACCOUNT: '{{ .Values.secrets.azure_account | b64enc }}'
  - AZURE_TABLE_NAME: '{{ .Values.secrets.azure_table_name | b64enc }}'
  - AZURE_CRYPTO_KEY: '{{ .Values.secrets.azure_crypto_key | b64enc }}'
  - AZURE_SIGNING_KEY: '{{ .Values.secrets.azure_signing_key | b64enc }}'
  - LEVEL: '{{ .Values.secrets.level | b64enc }}'
  - PORT: '{{ .Values.secrets.port | b64enc }}'
  - FORCE_SSL: '{{ .Values.secrets.force_ssl | b64enc }}'
  - AWS_ACCESS_KEY_ID: '{{ .Values.secrets.aws_access_key_id | b64enc }}'
  - AWS_SECRET_ACCESS_KEY: '{{ .Values.secrets.aws_secret_access_key | b64enc }}'
