apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-ui
data:
  APPLICATION_NAME: '{{ if .Values.ui.application_name }}{{ .Values.ui.application_name | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
