apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-hooks-scheduler
spec:
  selector:
    matchLabels:
      application: taskcluster
      taskcluster-service: taskcluster-hooks
      taskcluster-proc: scheduler
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-hooks-secret.yaml") . | sha256sum }}'
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-hooks
        taskcluster-proc: scheduler
    spec:
      serviceAccountName: taskcluster-hooks
      containers:
        - name: taskcluster-hooks
          image: .Values.dockerImage
          imagePullPolicy: Always
          args:
            - hooks/scheduler
          resources:
            requests:
              cpu: 1
              memory: 1
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: .Values.rootUrl
          envFrom:
            - secretRef:
                name: taskcluster-hooks
          ports: []
