apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-index-expire
  labels:
    app.kubernetes.io/name: taskcluster-index
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: index-expire
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  schedule: 0 0 * * *
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: taskcluster-index
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: index-expire
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: taskcluster-index
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: index-expire
            app.kubernetes.io/part-of: taskcluster
            app.kubernetes.io/managed-by: helm
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 86400
          containers:
            - name: taskcluster-index-expire
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - index/expire
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
              envFrom:
                - secretRef:
                    name: taskcluster-index
