apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-queue
data:
  - PUBLIC_BLOB_ARTIFACT_BUCKET: '{{ .Values.queue.public_blob_artifact_bucket | b64enc }}'
  - PRIVATE_BLOB_ARTIFACT_BUCKET: '{{ .Values.queue.private_blob_artifact_bucket | b64enc }}'
  - BLOB_ARTIFACT_REGION: '{{ .Values.queue.blob_artifact_region | b64enc }}'
  - PUBLIC_ARTIFACT_BUCKET: '{{ .Values.queue.public_artifact_bucket | b64enc }}'
  - PRIVATE_ARTIFACT_BUCKET: '{{ .Values.queue.private_artifact_bucket | b64enc }}'
  - AZURE_REPORT_CHANCE: '{{ .Values.queue.azure_report_chance | b64enc }}'
  - AZURE_REPORT_THRESHOLD: '{{ .Values.queue.azure_report_threshold | b64enc }}'
  - PUBLIC_ARTIFACT_EC2_PROXIES: '{{ .Values.queue.public_artifact_ec2_proxies | b64enc }}'
  - PUBLIC_ARTIFACT_BUCKET_CDN: '{{ .Values.queue.public_artifact_bucket_cdn | b64enc }}'
  - USE_CLOUD_MIRROR: '{{ .Values.queue.use_cloud_mirror | b64enc }}'
  - TASKCLUSTER_ROOT_URL: '{{ .Values.queue.taskcluster_root_url | b64enc }}'
  - TASKCLUSTER_CLIENT_ID: '{{ .Values.queue.taskcluster_client_id | b64enc }}'
  - TASKCLUSTER_ACCESS_TOKEN: '{{ .Values.queue.taskcluster_access_token | b64enc }}'
  - LEVEL: '{{ .Values.queue.level | b64enc }}'
  - PORT: '{{ .Values.queue.port | b64enc }}'
  - NODE_ENV: '{{ .Values.queue.node_env | b64enc }}'
  - FORCE_SSL: '{{ .Values.queue.force_ssl | b64enc }}'
  - AZURE_ACCOUNT_ID: '{{ .Values.queue.azure_account_id | b64enc }}'
  - AZURE_ACCOUNT_KEY: '{{ .Values.queue.azure_account_key | b64enc }}'
  - AZURE_TABLE_ACCOUNT_NAME: '{{ .Values.queue.azure_table_account_name | b64enc }}'
  - PULSE_NAMESPACE: '{{ .Values.queue.pulse_namespace | b64enc }}'
  - PULSE_USERNAME: '{{ .Values.queue.pulse_username | b64enc }}'
  - PULSE_PASSWORD: '{{ .Values.queue.pulse_password | b64enc }}'
  - PULSE_HOSTNAME: '{{ .Values.queue.pulse_hostname | b64enc }}'
  - PULSE_VHOST: '{{ .Values.queue.pulse_vhost | b64enc }}'
  - AWS_ACCESS_KEY_ID: '{{ .Values.queue.aws_access_key_id | b64enc }}'
  - AWS_SECRET_ACCESS_KEY: '{{ .Values.queue.aws_secret_access_key | b64enc }}'
  - ARTIFACT_REGION: '{{ .Values.queue.artifact_region | b64enc }}'
