apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-auth
data:
  TASKCLUSTER_ROOT_URL: '{{ .Values.auth.taskcluster_root_url | toJson | trimAll "\"" | b64enc }}'
  CLIENT_TABLE_NAME: '{{ .Values.auth.client_table_name | toJson | trimAll "\"" | b64enc }}'
  ROLES_CONTAINER_NAME: '{{ .Values.auth.roles_container_name | toJson | trimAll "\"" | b64enc }}'
  STATIC_CLIENTS: '{{ .Values.auth.static_clients | toJson | trimAll "\"" | b64enc }}'
  AZURE_ACCOUNTS: '{{ .Values.auth.azure_accounts | toJson | trimAll "\"" | b64enc }}'
  SENTRY_ORGANIZATION: '{{ .Values.auth.sentry_organization | toJson | trimAll "\"" | b64enc }}'
  SENTRY_HOST: '{{ .Values.auth.sentry_host | toJson | trimAll "\"" | b64enc }}'
  SENTRY_AUTH_TOKEN: '{{ .Values.auth.sentry_auth_token | toJson | trimAll "\"" | b64enc }}'
  SENTRY_TEAM: '{{ .Values.auth.sentry_team | toJson | trimAll "\"" | b64enc }}'
  SENTRY_KEY_PREFIX: '{{ .Values.auth.sentry_key_prefix | toJson | trimAll "\"" | b64enc }}'
  STATSUM_API_SECRET: '{{ .Values.auth.statsum_api_secret | toJson | trimAll "\"" | b64enc }}'
  STATSUM_BASE_URL: '{{ .Values.auth.statsum_base_url | toJson | trimAll "\"" | b64enc }}'
  WEBSOCKTUNNEL_SECRET: '{{ .Values.auth.websocktunnel_secret | toJson | trimAll "\"" | b64enc }}'
  DOCS_BUCKET: '{{ .Values.auth.docs_bucket | toJson | trimAll "\"" | b64enc }}'
  SCHEMAS_BUCKET: '{{ .Values.auth.schemas_bucket | toJson | trimAll "\"" | b64enc }}'
  REFS_BUCKET: '{{ .Values.auth.refs_bucket | toJson | trimAll "\"" | b64enc }}'
  AUDIT_LOG: '{{ .Values.auth.audit_log | toJson | trimAll "\"" | b64enc }}'
  LEVEL: '{{ .Values.auth.level | toJson | trimAll "\"" | b64enc }}'
  PORT: '{{ .Values.auth.port | toJson | trimAll "\"" | b64enc }}'
  NODE_ENV: '{{ .Values.auth.node_env | toJson | trimAll "\"" | b64enc }}'
  FORCE_SSL: '{{ .Values.auth.force_ssl | toJson | trimAll "\"" | b64enc }}'
  TRUST_PROXY: '{{ .Values.auth.trust_proxy | toJson | trimAll "\"" | b64enc }}'
  AZURE_ACCOUNT: '{{ .Values.auth.azure_account | toJson | trimAll "\"" | b64enc }}'
  AZURE_ACCOUNT_KEY: '{{ .Values.auth.azure_account_key | toJson | trimAll "\"" | b64enc }}'
  AZURE_SIGNING_KEY: '{{ .Values.auth.azure_signing_key | toJson | trimAll "\"" | b64enc }}'
  AZURE_CRYPTO_KEY: '{{ .Values.auth.azure_crypto_key | toJson | trimAll "\"" | b64enc }}'
  PULSE_USERNAME: '{{ .Values.auth.pulse_username | toJson | trimAll "\"" | b64enc }}'
  PULSE_PASSWORD: '{{ .Values.auth.pulse_password | toJson | trimAll "\"" | b64enc }}'
  PULSE_HOSTNAME: '{{ .Values.auth.pulse_hostname | toJson | trimAll "\"" | b64enc }}'
  PULSE_VHOST: '{{ .Values.auth.pulse_vhost | toJson | trimAll "\"" | b64enc }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.auth.aws_access_key_id | toJson | trimAll "\"" | b64enc }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.auth.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}'
  AWS_REGION: '{{ .Values.auth.aws_region | toJson | trimAll "\"" | b64enc }}'
  GCP_CREDENTIALS: '{{ .Values.auth.gcp_credentials | toJson | trimAll "\"" | b64enc }}'
  TEST_BUCKET: '{{ .Values.auth.test_bucket | toJson | trimAll "\"" | b64enc }}'
