apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-secrets-web
spec:
  selector:
    matchLabels:
      application: taskcluster
      taskcluster-service: taskcluster-secrets
      taskcluster-proc: web
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-secrets-secret.yaml") . | sha256sum }}'
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-secrets
        taskcluster-proc: web
    spec:
      serviceAccountName: taskcluster-secrets
      containers:
        - name: taskcluster-secrets
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - secrets/web
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-secrets
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/secrets/v1/ping
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 3
