apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-login
data:
  TASKCLUSTER_ROOT_URL: '{{ if .Values.login.taskcluster_root_url }}{{ .Values.login.taskcluster_root_url | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  TASKCLUSTER_CLIENT_ID: '{{ if .Values.login.taskcluster_client_id }}{{ .Values.login.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ if .Values.login.taskcluster_access_token }}{{ .Values.login.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AWS_ACCESS_KEY_ID: '{{ if .Values.login.aws_access_key_id }}{{ .Values.login.aws_access_key_id | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AWS_SECRET_ACCESS_KEY: '{{ if .Values.login.aws_secret_access_key }}{{ .Values.login.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  LEVEL: '{{ if .Values.login.level }}{{ .Values.login.level | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  PORT: '{{ if .Values.login.port }}{{ .Values.login.port | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  FORCE_SSL: '{{ if .Values.forceSSL }}{{ .Values.forceSSL | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  NODE_ENV: '{{ if .Values.nodeEnv }}{{ .Values.nodeEnv | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  TRUST_PROXY: '{{ if .Values.trustProxy }}{{ .Values.trustProxy | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AUTH0_DOMAIN: '{{ if .Values.login.auth0_domain }}{{ .Values.login.auth0_domain | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AUTH0_API_AUDIENCE: '{{ if .Values.login.auth0_api_audience }}{{ .Values.login.auth0_api_audience | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AUTH0_CLIENT_ID: '{{ if .Values.login.auth0_client_id }}{{ .Values.login.auth0_client_id | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AUTH0_CLIENT_SECRET: '{{ if .Values.login.auth0_client_secret }}{{ .Values.login.auth0_client_secret | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
