apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-notify
data:
  EMAIL_SOURCE_ADDRESS: '{{ .Values.notify.email_source_address | toJson | trimAll "\"" | b64enc }}'
  EMAIL_BLACKLIST: '{{ .Values.notify.email_blacklist | toJson | trimAll "\"" | b64enc }}'
  DENYLISTED_NOTIFICATION_TABLE_NAME: '{{ .Values.notify.denylisted_notification_table_name | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ROOT_URL: '{{ .Values.notify.taskcluster_root_url | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_CLIENT_ID: '{{ .Values.notify.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ .Values.notify.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}'
  AZURE_ACCOUNT_ID: '{{ .Values.azureAccountId | toJson | trimAll "\"" | b64enc }}'
  LEVEL: '{{ .Values.notify.level | toJson | trimAll "\"" | b64enc }}'
  PORT: '{{ .Values.notify.port | toJson | trimAll "\"" | b64enc }}'
  NODE_ENV: '{{ .Values.notify.node_env | toJson | trimAll "\"" | b64enc }}'
  FORCE_SSL: '{{ .Values.notify.force_ssl | toJson | trimAll "\"" | b64enc }}'
  TRUST_PROXY: '{{ .Values.notify.trust_proxy | toJson | trimAll "\"" | b64enc }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.notify.aws_access_key_id | toJson | trimAll "\"" | b64enc }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.notify.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}'
  AWS_REGION: '{{ .Values.notify.aws_region | toJson | trimAll "\"" | b64enc }}'
  PULSE_NAMESPACE: '{{ .Values.notify.pulse_namespace | toJson | trimAll "\"" | b64enc }}'
  PULSE_HOSTNAME: '{{ .Values.pulseHostname | toJson | trimAll "\"" | b64enc }}'
  PULSE_USERNAME: '{{ .Values.notify.pulse_username | toJson | trimAll "\"" | b64enc }}'
  PULSE_PASSWORD: '{{ .Values.notify.pulse_password | toJson | trimAll "\"" | b64enc }}'
  PULSE_VHOST: '{{ .Values.pulseVhost | toJson | trimAll "\"" | b64enc }}'
  IRC_SERVER: '{{ .Values.notify.irc_server | toJson | trimAll "\"" | b64enc }}'
  IRC_NICK: '{{ .Values.notify.irc_nick | toJson | trimAll "\"" | b64enc }}'
  IRC_USER_NAME: '{{ .Values.notify.irc_user_name | toJson | trimAll "\"" | b64enc }}'
  IRC_REAL_NAME: '{{ .Values.notify.irc_real_name | toJson | trimAll "\"" | b64enc }}'
  IRC_PASSWORD: '{{ .Values.notify.irc_password | toJson | trimAll "\"" | b64enc }}'
  IRC_PORT: '{{ .Values.notify.irc_port | toJson | trimAll "\"" | b64enc }}'
  IRC_DEBUG: '{{ .Values.notify.irc_debug | toJson | trimAll "\"" | b64enc }}'
  IRC_PULSE_QUEUE_NAME: '{{ .Values.notify.irc_pulse_queue_name | toJson | trimAll "\"" | b64enc }}'
