apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-index
data:
  AZURE_ACCOUNT: '{{ .Values.index.azure_account | b64enc }}'
  LEVEL: '{{ .Values.index.level | b64enc }}'
  PORT: '{{ .Values.index.port | b64enc }}'
  TASKCLUSTER_ROOT_URL: '{{ .Values.index.taskcluster_root_url | b64enc }}'
  TASKCLUSTER_CLIENT_ID: '{{ .Values.index.taskcluster_client_id | b64enc }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ .Values.index.taskcluster_access_token | b64enc }}'
  PULSE_HOSTNAME: '{{ .Values.index.pulse_hostname | b64enc }}'
  PULSE_USERNAME: '{{ .Values.index.pulse_username | b64enc }}'
  PULSE_PASSWORD: '{{ .Values.index.pulse_password | b64enc }}'
  PULSE_VHOST: '{{ .Values.index.pulse_vhost | b64enc }}'
  PULSE_NAMESPACE: '{{ .Values.index.pulse_namespace | b64enc }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.index.aws_access_key_id | b64enc }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.index.aws_secret_access_key | b64enc }}'
  FORCE_SSL: '{{ .Values.index.force_ssl | b64enc }}'
  TRUST_PROXY: '{{ .Values.index.trust_proxy | b64enc }}'
