apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-secrets-expire
spec:
  schedule: 0 * * * *
  jobTemplate:
    metadata:
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-secrets
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 600
          containers:
            - name: taskcluster-secrets-expire
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - secrets/expire
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
              envFrom:
                - secretRef:
                    name: taskcluster-secrets
