apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-secrets
data:
  TASKCLUSTER_ROOT_URL: '{{ if .Values.secrets.taskcluster_root_url }}{{ .Values.secrets.taskcluster_root_url | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  TASKCLUSTER_CLIENT_ID: '{{ if .Values.secrets.taskcluster_client_id }}{{ .Values.secrets.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ if .Values.secrets.taskcluster_access_token }}{{ .Values.secrets.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AZURE_ACCOUNT_ID: '{{ if .Values.azureAccountId }}{{ .Values.azureAccountId | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AZURE_TABLE_NAME: '{{ if .Values.secrets.azure_table_name }}{{ .Values.secrets.azure_table_name | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AZURE_CRYPTO_KEY: '{{ if .Values.secrets.azure_crypto_key }}{{ .Values.secrets.azure_crypto_key | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AZURE_SIGNING_KEY: '{{ if .Values.secrets.azure_signing_key }}{{ .Values.secrets.azure_signing_key | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  LEVEL: '{{ if .Values.secrets.level }}{{ .Values.secrets.level | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  PORT: '{{ if .Values.secrets.port }}{{ .Values.secrets.port | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  FORCE_SSL: '{{ if .Values.forceSSL }}{{ .Values.forceSSL | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AWS_ACCESS_KEY_ID: '{{ if .Values.secrets.aws_access_key_id }}{{ .Values.secrets.aws_access_key_id | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
  AWS_SECRET_ACCESS_KEY: '{{ if .Values.secrets.aws_secret_access_key }}{{ .Values.secrets.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}{{ else }}{{ end }}'
