apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-purge-cache
data:
  LEVEL: '{{ .Values.purge_cache.level | toJson | trimAll "\"" | b64enc }}'
  PORT: '{{ .Values.purge_cache.port | toJson | trimAll "\"" | b64enc }}'
  FORCE_SSL: '{{ .Values.purge_cache.force_ssl | toJson | trimAll "\"" | b64enc }}'
  TRUST_PROXY: '{{ .Values.purge_cache.trust_proxy | toJson | trimAll "\"" | b64enc }}'
  AZURE_ACCOUNT_ID: '{{ .Values.azureAccountId | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ROOT_URL: '{{ .Values.purge_cache.taskcluster_root_url | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_CLIENT_ID: '{{ .Values.purge_cache.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ .Values.purge_cache.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.purge_cache.aws_access_key_id | toJson | trimAll "\"" | b64enc }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.purge_cache.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}'
