apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-notify-irc
spec:
  selector:
    matchLabels:
      application: taskcluster
      taskcluster-service: taskcluster-notify
      taskcluster-proc: irc
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-notify-secret.yaml") . | sha256sum }}'
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-notify
        taskcluster-proc: irc
    spec:
      serviceAccountName: taskcluster-notify
      containers:
        - name: taskcluster-notify
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - notify/irc
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-notify
          ports: []
