apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-hooks-expires
  labels:
    app.kubernetes.io/name: taskcluster-hooks
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: hooks-expires
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  schedule: 10 0 * * *
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: taskcluster-hooks
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: hooks-expires
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: taskcluster-hooks
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: hooks-expires
            app.kubernetes.io/part-of: taskcluster
            app.kubernetes.io/managed-by: helm
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 86400
          containers:
            - name: taskcluster-hooks-expires
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - hooks/expires
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
              envFrom:
                - secretRef:
                    name: taskcluster-hooks
