apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-github-worker
spec:
  selector:
    matchLabels:
      application: taskcluster
      taskcluster-service: taskcluster-github
      taskcluster-proc: worker
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-github-secret.yaml") . | sha256sum }}'
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-github
        taskcluster-proc: worker
    spec:
      serviceAccountName: taskcluster-github
      containers:
        - name: taskcluster-github
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - github/worker
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-github
          ports: []
