apiVersion: v1
kind: Service
metadata:
  name: taskcluster-references
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    application: taskcluster
    taskcluster-proc: web
    taskcluster-service: taskcluster-references
  type: NodePort
