apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-built-in-workers-server
spec:
  selector:
    matchLabels:
      application: taskcluster
      taskcluster-service: taskcluster-built-in-workers
      taskcluster-proc: server
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-built-in-workers-secret.yaml") . | sha256sum }}'
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-built-in-workers
        taskcluster-proc: server
    spec:
      serviceAccountName: taskcluster-built-in-workers
      containers:
        - name: taskcluster-built-in-workers
          image: .Values.dockerImage
          imagePullPolicy: Always
          args:
            - built-in-workers/server
          resources:
            requests:
              cpu: 1
              memory: 1
          env:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: .Values.rootUrl
          envFrom:
            - secretRef:
                name: taskcluster-built-in-workers
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/built-in-workers/v1/ping
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 3
