apiVersion: v1
data:
  DEBUG: '{{ "*" | b64enc }}'
  JWT_KEY: '{{ .Values.jwtKey | b64enc }}'
  LEVEL: '{{ "DEBUG" | b64enc }}'
  NODE_ENV: '{{ "production" | b64enc }}'
  PUBLIC_URL: '{{ .Values.rootUrl | b64enc }}'
  PULSE_HOSTNAME: '{{ .Values.tfRabbitmqHostname | b64enc }}'
  PULSE_PASSWORD: '{{ .Values.webServerPulsePassword | b64enc }}'
  PULSE_USERNAME: '{{ .Values.webServerPulseUsername | b64enc }}'
  PULSE_VHOST: '{{ .Values.pulseVhost | b64enc }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ .Values.webServerAccessToken | b64enc }}'
  TASKCLUSTER_CLIENT_ID: '{{ "static/taskcluster/web-server" | b64enc }}'
  UI_LOGIN_STRATEGIES: '{{ .Values.uiLoginStrategies | b64enc }}'
kind: Secret
metadata:
  name: taskcluster-web-server
type: Opaque
