apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: taskcluster-built-in-workers-secrets-read
rules:
- apiGroups:
  - ''
  resources:
  - secrets/taskcluster-built-in-workers
  verbs:
  - get
  - watch
  - list
