apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: taskcluster-built-in-workers-server
spec:
  replicas: 1.0
  selector:
    matchLabels:
      application: taskcluster
      taskcluster-proc: server
      taskcluster-service: taskcluster-built-in-workers
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-built-in-workers-secrets.yaml") . | sha256sum }}'
      labels:
        application: taskcluster
        taskcluster-proc: server
        taskcluster-service: taskcluster-built-in-workers
    spec:
      containers:
      - args:
        - built-in-workers/server
        env:
        - name: TASKCLUSTER_ROOT_URL
          value: '{{ .Values.rootUrl }}'
        envFrom:
        - secretRef:
            name: taskcluster-built-in-workers
        image: '{{ .Values.dockerImage }}'
        imagePullPolicy: Always
        name: taskcluster-built-in-workers
        ports: []
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
      serviceAccountName: taskcluster-built-in-workers
