apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: '{{ .Values.authAwsAccessKeyId | b64enc }}'
  AWS_REGION: '{{ .Values.tfAwsRegion | b64enc }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.authAwsSecretAccessKey | b64enc }}'
  AZURE_ACCOUNT: '{{ .Values.tfAzureAccount | b64enc }}'
  AZURE_ACCOUNTS: '{{ .Values.azureAccounts | b64enc }}'
  AZURE_ACCOUNT_KEY: '{{ .Values.azureAccountKey | b64enc }}'
  AZURE_CRYPTO_KEY: '{{ .Values.authAzureCryptoKey | b64enc }}'
  AZURE_SIGNING_KEY: '{{ .Values.authAzureSigningKey | b64enc }}'
  DEBUG: '{{ "*" | b64enc }}'
  FORCE_SSL: '{{ "false" | b64enc }}'
  LEVEL: '{{ "DEBUG" | b64enc }}'
  LOCK_ROLES: '{{ "false" | b64enc }}'
  NODE_ENV: '{{ "production" | b64enc }}'
  PROFILE: '{{ "production" | b64enc }}'
  PULSE_HOSTNAME: '{{ .Values.tfRabbitmqHostname | b64enc }}'
  PULSE_PASSWORD: '{{ .Values.authPulsePassword | b64enc }}'
  PULSE_USERNAME: '{{ .Values.authPulseUsername | b64enc }}'
  PULSE_VHOST: '{{ .Values.pulseVhost | b64enc }}'
  STATIC_CLIENTS: '{{ .Values.staticClients | b64enc }}'
  TRUST_PROXY: '{{ "true" | b64enc }}'
  WEBSOCKTUNNEL_SECRET: '{{ .Values.websocktunnelSecret | b64enc }}'
kind: Secret
metadata:
  name: taskcluster-auth
type: Opaque
