apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-auth-purgeexpiredclients
spec:
  schedule: 0 0 * * *
  jobTemplate:
    metadata:
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-auth
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 86400
          containers:
            - name: taskcluster-auth-purgeexpiredclients
              image: .Values.dockerImage
              imagePullPolicy: Always
              args:
                - auth/purgeExpiredClients
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: .Values.rootUrl
              envFrom:
                - secretRef:
                    name: taskcluster-auth
