apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-secrets-expire
spec:
  jobTemplate:
    metadata:
      labels:
        application: taskcluster
        taskcluster-service: taskcluster-secrets
    spec:
      template:
        spec:
          activeDeadlineSeconds: 600
          containers:
          - args:
            - secrets/expire
            env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
            envFrom:
            - secretRef:
                name: taskcluster-secrets
            image: '{{ .Values.dockerImage }}'
            imagePullPolicy: Always
            name: taskcluster-secrets-expire
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
          restartPolicy: OnFailure
  schedule: 0 * * * *
