defaults:
  app:
    sourceEmail:                  !env EMAIL_SOURCE_ADDRESS
    routePrefix:                  notify
    # Rate limits for email: maximum average rate of count/time
    # 50 per 10 minute is a reasonable default: someone with an exploding
    # taskgraph will get 50 messages, and will be able to get another 50
    # when they try again after 10 minutes.
    maxMessageCount:              50
    maxMessageTime:               600
    # Email address to blacklist, useful to mitigate temporary misuse
    emailBlacklist:               !env:json EMAIL_BLACKLIST
    denylistedNotificationTableName: !env DENYLISTED_NOTIFICATION_TABLE_NAME
    # ignore tasks with reasonResolved matching something in this list
    ignoreTaskReasonResolved:
        - canceled
        - deadline-exceeded

  taskcluster:
    rootUrl:          !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId:       !env TASKCLUSTER_CLIENT_ID
      accessToken:    !env TASKCLUSTER_ACCESS_TOKEN

  azure:
    accountId:                    !env AZURE_ACCOUNT_ID

  monitoring:
    level: !env LEVEL

  server:
    port:             !env:number PORT
    env:              !env NODE_ENV
    forceSSL:         !env:bool FORCE_SSL
    trustProxy:       !env:bool TRUST_PROXY

  aws:
    accessKeyId:      !env AWS_ACCESS_KEY_ID
    secretAccessKey:  !env AWS_SECRET_ACCESS_KEY
    region:           !env AWS_REGION

  pulse:
    namespace: !env PULSE_NAMESPACE
    hostname: !env PULSE_HOSTNAME
    username: !env PULSE_USERNAME
    password: !env PULSE_PASSWORD
    vhost: !env PULSE_VHOST

  irc:
    server:           !env IRC_SERVER
    nick:             !env IRC_NICK
    userName:         !env IRC_USER_NAME
    realName:         !env IRC_REAL_NAME
    password:         !env IRC_PASSWORD
    port:             !env IRC_PORT
    debug:            !env IRC_DEBUG
    pulseQueueName:   !env IRC_PULSE_QUEUE_NAME

# Configuration in production
production:
  server:
    env:              production
  irc:
    port:             6697
    pulseQueueName:   irc-notifications
  pulse:
    namespace: taskcluster-notify

# Configuration of tests
test:
  aws:
    region:           us-east-1
  app:
    sourceEmail: '"Taskcluster Notify Testing" <taskcluster-noreply-testing@mozilla.com>'
    sqsQueueName: taskcluster-notify-test-irc
    routePrefix: test-notify
    denylistedNotificationTableName: TestDenylistedNotification
    emailBlacklist: []
  azure:
    accountId:        'jungle'
  server:
    port:             60401
    env:              development
    forceSSL:         false
    trustProxy:       true
  irc:
    server:           irc.mozilla.org
    nick:             taskcluster-test
    userName:         taskcluster-test
    realName:         Taskcluster Test Robot
    port:             6697
    pulseQueueName:   irc-test-notifications
